# Generated by Django 6.0.3 on 2026-03-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodcheckin',
            name='sleep_hours',
            field=models.FloatField(default=7.0),
        ),
        migrations.AddField(
            model_name='moodcheckin',
            name='stress_level',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='current_risk_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='risk_band',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=50),
        ),
    ]
